// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Dtos
{
    public partial class ProductSizeCategoryDTO
    {
        public int ProductSizeCategoryId { get; set; }
        public string Title { get; set; }
        public int? CreateBy { get; set; }
        public DateTime? CreateTime { get; set; }
    }
}