// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models
{
    public partial class ProductCategory
    {
        public int ProductCategoryId { get; set; }
        public string Title { get; set; }
        public bool? Status { get; set; }
        public string Image { get; set; }
        public int? CreateBy { get; set; }
        public DateTime? CreateTime { get; set; }
        public int? Position { get; set; }
    }
}