// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models
{
    public partial class ProductStatus
    {
        public ProductStatus()
        {
            Cart = new HashSet<Cart>();
        }

        public int ProductStatusId { get; set; }
        public int? ProductId { get; set; }
        public int? ProductSizeCategoryId { get; set; }
        public int? ColorCategoryId { get; set; }
        public int? Quantity { get; set; }
        public int? CreateBy { get; set; }
        public DateTime? CreateTime { get; set; }

        public virtual ColorCategory ColorCategory { get; set; }
        public virtual User CreateByNavigation { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductSizeCategory ProductSizeCategory { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
    }
}