// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models
{
    public partial class User
    {
        public User()
        {
            Cart = new HashSet<Cart>();
            Product = new HashSet<Product>();
            ProductStatus = new HashSet<ProductStatus>();
        }

        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public bool? Status { get; set; }
        public int? RoleId { get; set; }
        public DateTime? CreateTime { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<ProductStatus> ProductStatus { get; set; }
    }
}